<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 defined('BASEPATH') OR exit('No direct script access allowed');
header('Access-Control-Allow-Origin: *');
class Village_recovery extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->helper('url_helper');
        $this->load->model('Recovery_model');
        $this->load->model('Category_model');
        $this->load->model('Login_model');  
        $this->load->model('Village_model'); 
        $this->load->model('Village_recovery_model'); 
        $this->load->model('Recovery_collection_model'); 
       
    } 

    /*
     * Listing of recoverys
     */
    function index()
    {
        $username= $this->session->userdata("username");
        $village=$this->Village_model->get_village_by_username($username);
        if($village!=null){
            $this->load->library('form_validation');
            $village_id=  $village["village_id"];
            $this->form_validation->set_rules('recovery_id','recovery_id','required'); 
             
                
             if($this->form_validation->run())     
             {  
               
               $params = array(
                'fk_recovery_id'=> $this->input->post('recovery_id'),
                'fk_village_id'=> $village_id,
            
            
             );
                 
             $recovery_id = $this->Village_recovery_model->add_village_recovery($params);
             
              
              
              }
    
            $params['limit'] = RECORDS_PER_PAGE; 
            $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
            
            $config = $this->config->item('pagination');
            $config['base_url'] = site_url('index.php/recovery/index?');
            $config['total_rows'] = $this->Recovery_model->get_all_recovery_count();
            $this->pagination->initialize($config);
    
            $data['recovery'] = $this->Recovery_model->get_add_recovery_join_query($params);
            $data['all_village_recovery'] = $this->Village_recovery_model->get_village_recovery_by_village_id($village_id);
            $data['offset']=$params['offset'];
            $data['_view'] = 'village_recovery/index';
            $this->load->view('layouts/main',$data);
        }else{

            die("No Village found");
        }
        
	 
    }
   

    function new_monthly_recovery(){
        $data['_view'] = 'village_recovery/new_monthly_recovery';
            $this->load->view('layouts/main',$data);
    }

    function show_monthly_recovery(){
        $usertype= $this->session->userdata("usertype");
        $username= $this->session->userdata("username");
       
       

        if($usertype=="admin"){
            $data["villages"]=  $this->Village_model->get_all_village();
        }else{
            $village[]=$this->Village_model->get_village_by_username($username);
            $data["villages"]=  $village;
        }

        $data['_view'] = 'village_recovery/show_monthly_recovery';
            $this->load->view('layouts/main',$data);
    }

    function admin_show_village_recovery(){
        $data['_view'] = 'village_recovery/admin_show_village_recovery';
        $usertype= $this->session->userdata("usertype");
        $username= $this->session->userdata("username");
       
       

        if($usertype=="admin"){
            $data["villages"]=  $this->Village_model->get_all_village();
        }else{
            $village[]=$this->Village_model->get_village_by_username($username);
            $data["villages"]=  $village;
        }



            $this->load->view('layouts/main',$data);
    }
    
    function admin_show_village_summary(){
        $data['_view'] = 'village_recovery/admin_show_village_summary';
        $data["villages"]=  $this->Village_model->get_all_village();
            $this->load->view('layouts/main',$data);
    }
    


    function searchMonthlyRecovery(){

        
        $this->load->model('Monthly_edit_model');   
        $all_village_recovery=array();
        $month=$this->input->post('month');
        $year=$this->input->post('year');
        $village_id=$this->input->post('village_id');
        $username= $this->session->userdata("username");
        $usertype= $this->session->userdata("usertype");
        

        $village=$this->Village_model->get_village($village_id);
        $edit_value=$this->Monthly_edit_model->get_Monthly_edit_month_year($month,$year);

        $edit_last_date= $edit_value!=null ? $edit_value['date'] : date('Y-m-d');

        $cur_date= date("Y-m-d");
        $diff = strtotime($edit_last_date) - strtotime($cur_date);
  
        // 1 day = 24 hours
        // 24 * 60 * 60 = 86400 seconds
        $day= (round($diff / 86400));

        $responds=array();
       
        if($village!=null){

            

            $village_id=  $village["village_id"];
            $all_village_recovery =  $this->Recovery_collection_model->get_village_recovery_collection_by_village_id($village_id,$month,$year);
        }
        if($usertype=="admin"){
            $responds['edit_status']= true;
        }else{
            $responds['edit_status']= $day>=0 ? true: false;
        }
       
        $responds['data']= $all_village_recovery;
        
        echo json_encode($responds);
    }


    function searchAdminMonthlyRecovery(){

        $final_result=array();
        $all_village_recovery=array();
        $month=$this->input->post('month');
        $year=$this->input->post('year');
        $village_id=$this->input->post('village_id');
        $categories=$this->Category_model->get_all_category();
        if($village_id=="ALL"){
            $grand_params["b"]=0;
            $grand_params["c"]=0;
            $grand_params["d"]=0;
            $grand_params["e"]=0;
            $grand_params["f"]=0;
            $grand_params["g"]=0;
            $grand_params["h"]=0;
            $grand_params["i"]=0;
            $grand_params["j"]=0;
            $grand_params["k"]=0;
             $grand_params["l"]=0;
             $grand_params["m"]=0;
             $grand_params["n"]=0;
             $grand_params["o"]=0;
             $grand_params["p"]=0;
             $grand_params["q"]=0;
             $grand_params["r"]=0;
             $grand_params["s"]=0;
             $grand_params["t"]=0;
             $grand_params["u"]=0;
             $grand_params["v"]=0;
             $grand_params["w"]=0;
             $grand_params["x"]=0;
             $grand_params["y"]=0;
             $grand_params["z"]=0;
             $grand_params["aa"]=0;
             $grand_params["ab"]=0;
             $grand_params["ac"]=0;
             $grand_params["ad"]=0;
             $grand_params["ae"]=0;
             $grand_params["af"]=0;
             $grand_params["ag"]=0;
             $grand_params["ah"]=0;
             foreach($categories as $cat){
                $all_village_recovery =array();
                $cat_id= $cat["category_id"];
                $all_village_recovery =  $this->Recovery_model->get_recovery_cat($cat_id);
                $all_village_recovery_temp=array();
                foreach( $all_village_recovery as $vr){
                  
                    $vr["b"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("b",$month,$year, $vr["recovery_id"]);;
                    $vr["c"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("c",$month,$year, $vr["recovery_id"]);;
                    $vr["d"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("d",$month,$year, $vr["recovery_id"]);;
                    $vr["e"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("e",$month,$year, $vr["recovery_id"]);;
                    $vr["f"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("f",$month,$year, $vr["recovery_id"]);;
                    $vr["g"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("g",$month,$year, $vr["recovery_id"]);;
                    $vr["h"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("h",$month,$year, $vr["recovery_id"]);;
                    $vr["i"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("i",$month,$year, $vr["recovery_id"]);;
                    $vr["j"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("j",$month,$year, $vr["recovery_id"]);;
                    $vr["k"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("k",$month,$year, $vr["recovery_id"]);;
                    $vr["l"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("l",$month,$year, $vr["recovery_id"]);;
                    $vr["m"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("m",$month,$year, $vr["recovery_id"]);;
                    $vr["n"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("n",$month,$year, $vr["recovery_id"]);;
                    $vr["o"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("o",$month,$year, $vr["recovery_id"]);;
                    $vr["p"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("p",$month,$year, $vr["recovery_id"]);;
                    $vr["q"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("q",$month,$year, $vr["recovery_id"]);;
                    $vr["r"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("r",$month,$year, $vr["recovery_id"]);;
                    $vr["s"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("s",$month,$year, $vr["recovery_id"]);;
                    $vr["t"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("t",$month,$year, $vr["recovery_id"]);;
                    $vr["u"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("u",$month,$year, $vr["recovery_id"]);;
                    $vr["v"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("v",$month,$year, $vr["recovery_id"]);;
                    $vr["w"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("w",$month,$year, $vr["recovery_id"]);;
                    $vr["x"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("x",$month,$year, $vr["recovery_id"]);;
                    $vr["y"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("y",$month,$year, $vr["recovery_id"]);;
                    $vr["z"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("z",$month,$year, $vr["recovery_id"]);;
                    $vr["aa"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("aa",$month,$year, $vr["recovery_id"]);;
                    $vr["ab"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("ab",$month,$year, $vr["recovery_id"]);;
                    $vr["ac"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("ac",$month,$year, $vr["recovery_id"]);;
                    $vr["ad"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("ad",$month,$year, $vr["recovery_id"]);;
                    $vr["ae"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("ae",$month,$year, $vr["recovery_id"]);;
                    $vr["af"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("af",$month,$year, $vr["recovery_id"]);;
                    $vr["ag"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("ag",$month,$year, $vr["recovery_id"]);;
                    $vr["ah"]=$this->Recovery_collection_model->get_summary_sum_by_recovery("ah",$month,$year, $vr["recovery_id"]);;

                    // grand total
                    $grand_params["b"]+= $vr['b'];
                    $grand_params["c"]+= $vr['c'];
                    $grand_params["d"]+= $vr['d'];
                    $grand_params["e"]+= $vr['e'];
                    $grand_params["f"]+= $vr['f'];
                    $grand_params["g"]+= $vr['g'];
                    $grand_params["h"]+= $vr['h'];
                    $grand_params["i"]+= $vr['i'];
                    $grand_params["j"]+= $vr['j'];
                    $grand_params["k"]+= $vr['k'];
                    $grand_params["l"]+= $vr['l'];
                    $grand_params["m"]+= $vr['m'];
                    $grand_params["n"]+= $vr['n'];
                    $grand_params["o"]+= $vr['o'];
                    $grand_params["p"]+= $vr['p'];
                    $grand_params["q"]+= $vr['q'];
                    $grand_params["r"]+= $vr['r'];
                    $grand_params["s"]+= $vr['s'];
                    $grand_params["t"]+= $vr['t'];
                    $grand_params["u"]+= $vr['u'];
                    $grand_params["v"]+= $vr['v'];
                    $grand_params["w"]+= $vr['w'];
                    $grand_params["x"]+= $vr['x'];
                    $grand_params["y"]+= $vr['y'];
                    $grand_params["z"]+= $vr['z'];
                    $grand_params["aa"]+= $vr['aa'];
                    $grand_params["ab"]+= $vr['ab'];
                    $grand_params["ac"]+= $vr['ac'];
                    $grand_params["ad"]+= $vr['ad'];
                    $grand_params["ae"]+= $vr['ae'];
                    $grand_params["af"]+= $vr['af'];
                    $grand_params["ag"]+= $vr['ag'];

                    $all_village_recovery_temp[]=$vr;
                }
                $cat['recovery']=$all_village_recovery_temp;
                $cat['total']=$grand_params;
              
            
                $final_result[]=$cat;
             }





        }else{
        $village=$this->Village_model->get_village($village_id);
        if($village!=null){
                $grand_params["b"]=0;
                $grand_params["c"]=0;
                $grand_params["d"]=0;
                $grand_params["e"]=0;
                $grand_params["f"]=0;
                $grand_params["g"]=0;
                $grand_params["h"]=0;
                $grand_params["i"]=0;
                $grand_params["j"]=0;
                $grand_params["k"]=0;
                 $grand_params["l"]=0;
                 $grand_params["m"]=0;
                 $grand_params["n"]=0;
                 $grand_params["o"]=0;
                 $grand_params["p"]=0;
                 $grand_params["q"]=0;
                 $grand_params["r"]=0;
                 $grand_params["s"]=0;
                 $grand_params["t"]=0;
                 $grand_params["u"]=0;
                 $grand_params["v"]=0;
                 $grand_params["w"]=0;
                 $grand_params["x"]=0;
                 $grand_params["y"]=0;
                 $grand_params["z"]=0;
                 $grand_params["aa"]=0;
                 $grand_params["ab"]=0;
                 $grand_params["ac"]=0;
                 $grand_params["ad"]=0;
                 $grand_params["ae"]=0;
                 $grand_params["af"]=0;
                 $grand_params["ag"]=0;
                 $grand_params["ah"]=0;
            foreach($categories as $cat){
                $all_village_recovery =array();
                $cat_id= $cat["category_id"];
                $village_id=  $village["village_id"];
                $all_village_recovery =  $this->Recovery_collection_model->get_village_recovery_collection_by_cat_village_id($cat_id,$village_id,$month,$year);
             
                $params["b"]=0;
                $params["c"]=0;
                $params["d"]=0;
                $params["e"]=0;
                $params["f"]=0;
                $params["g"]=0;
                $params["h"]=0;
                $params["i"]=0;
                $params["j"]=0;
                $params["k"]=0;
                 $params["l"]=0;
                 $params["m"]=0;
                 $params["n"]=0;
                 $params["o"]=0;
                 $params["p"]=0;
                 $params["q"]=0;
                 $params["r"]=0;
                 $params["s"]=0;
                 $params["t"]=0;
                 $params["u"]=0;
                 $params["v"]=0;
                 $params["w"]=0;
                 $params["x"]=0;
                 $params["y"]=0;
                 $params["z"]=0;
                 $params["aa"]=0;
                 $params["ab"]=0;
                 $params["ac"]=0;
                 $params["ad"]=0;
                 $params["ae"]=0;
                 $params["af"]=0;
                 $params["ag"]=0;
                 $params["ah"]=0;

                foreach( $all_village_recovery as $vr){
                  
                    $params["b"]+= $vr['b'];
                    $params["c"]+= $vr['c'];
                    $params["d"]+= $vr['d'];
                    $params["e"]+= $vr['e'];
                    $params["f"]+= $vr['f'];
                    $params["g"]+= $vr['g'];
                    $params["h"]+= $vr['h'];
                    $params["i"]+= $vr['i'];
                    $params["j"]+= $vr['j'];
                    $params["k"]+= $vr['k'];
                    $params["l"]+= $vr['l'];
                    $params["m"]+= $vr['m'];
                    $params["n"]+= $vr['n'];
                    $params["o"]+= $vr['o'];
                    $params["p"]+= $vr['p'];
                    $params["q"]+= $vr['q'];
                    $params["r"]+= $vr['r'];
                    $params["s"]+= $vr['s'];
                    $params["t"]+= $vr['t'];
                    $params["u"]+= $vr['u'];
                    $params["v"]+= $vr['v'];
                    $params["w"]+= $vr['w'];
                    $params["x"]+= $vr['x'];
                    $params["y"]+= $vr['y'];
                    $params["z"]+= $vr['z'];
                    $params["aa"]+= $vr['aa'];
                    $params["ab"]+= $vr['ab'];
                    $params["ac"]+= $vr['ac'];
                    $params["ad"]+= $vr['ad'];
                    $params["ae"]+= $vr['ae'];
                    $params["af"]+= $vr['af'];
                    $params["ag"]+= $vr['ag'];

                    // grand total
                    $grand_params["b"]+= $vr['b'];
                    $grand_params["c"]+= $vr['c'];
                    $grand_params["d"]+= $vr['d'];
                    $grand_params["e"]+= $vr['e'];
                    $grand_params["f"]+= $vr['f'];
                    $grand_params["g"]+= $vr['g'];
                    $grand_params["h"]+= $vr['h'];
                    $grand_params["i"]+= $vr['i'];
                    $grand_params["j"]+= $vr['j'];
                    $grand_params["k"]+= $vr['k'];
                    $grand_params["l"]+= $vr['l'];
                    $grand_params["m"]+= $vr['m'];
                    $grand_params["n"]+= $vr['n'];
                    $grand_params["o"]+= $vr['o'];
                    $grand_params["p"]+= $vr['p'];
                    $grand_params["q"]+= $vr['q'];
                    $grand_params["r"]+= $vr['r'];
                    $grand_params["s"]+= $vr['s'];
                    $grand_params["t"]+= $vr['t'];
                    $grand_params["u"]+= $vr['u'];
                    $grand_params["v"]+= $vr['v'];
                    $grand_params["w"]+= $vr['w'];
                    $grand_params["x"]+= $vr['x'];
                    $grand_params["y"]+= $vr['y'];
                    $grand_params["z"]+= $vr['z'];
                    $grand_params["aa"]+= $vr['aa'];
                    $grand_params["ab"]+= $vr['ab'];
                    $grand_params["ac"]+= $vr['ac'];
                    $grand_params["ad"]+= $vr['ad'];
                    $grand_params["ae"]+= $vr['ae'];
                    $grand_params["af"]+= $vr['af'];
                    $grand_params["ag"]+= $vr['ag'];

                }
                $cat['recovery']=$all_village_recovery;
                $cat['total']=$params;
              
            
                $final_result[]=$cat;
            }
            
        }
    }
        $responds['final_result']=$final_result;
        $responds['grand_result']=$grand_params;
         
        echo json_encode($responds);
    }
    

    function searchAdminMonthlySummary(){

        $final_result=array();
        $all_village_recovery=array();
        $month=$this->input->post('month');
        $year=$this->input->post('year');
        $villages =  $this->Village_model->get_all_village();
           $grand_total["collectable_demand"]=0;
            $grand_total["collection"]=0;
            $grand_total["collectable_balance"]=0;
            $grand_total["stay"]=0;
            $grand_total["percentage"]=0;
            
        foreach( $villages as $v){
            $v["collectable_demand"]=$this->Recovery_collection_model->get_summary("y",$month,$year, $v["village_id"]);
            $v["collection"]=$this->Recovery_collection_model->get_summary("ae",$month,$year, $v["village_id"]);;
            $v["collectable_balance"]=$this->Recovery_collection_model->get_summary("ag",$month,$year, $v["village_id"]);;;
            $v["stay"]=$this->Recovery_collection_model->get_summary("q",$month,$year, $v["village_id"]);;;
            $v["percentage"]=$this->Recovery_collection_model->get_summary("ah",$month,$year, $v["village_id"]);;;
            
            $final_result[]=$v;
            $grand_total["collectable_demand"] += $v["collectable_demand"];
            $grand_total["collection"] +=  $v["collection"];
            $grand_total["collectable_balance"] += $v["collectable_balance"];
            $grand_total["stay"] += $v["collectable_balance"];
         }
         $grand_total["percentage"]=  $grand_total["collectable_demand"]==0 ? "": ($grand_total["collection"]/$grand_total["collectable_demand"])*100;
    
        $responds['final_result']=$final_result;
        $responds['grand_result']= $grand_total;
         
        echo json_encode($responds);



   }
    function save_all_monthly_village_revenue(){
        $username= $this->session->userdata("username");
        $village=$this->Village_model->get_village_by_username($username);
        if($village!=null){
            $village_id=  $village["village_id"];
         $month=$this->input->post('month');
          $year=$this->input->post('year');
      
       $recoveries = $this->input->post('recoveries');

        foreach($recoveries as $row){
            
            $params=array();
            $params["month"]=$month;
            $params["year"]=$year;
            $params["fk_recovery_id"]=$row['recovery_id'];
            $params["fk_village_id"]=$village_id;
            $params["b"]=$row['b'];
            $params["c"]=$row['c'];
            $params["d"]=$row['d'];
            $params["e"]=$row['e'];
            $params["f"]=$row['f'];
            $params["g"]=$row['g'];
            $params["h"]=$row['h'];
            $params["i"]=$row['i'];
            $params["j"]=$row['j'];
            $params["k"]=$row['k'];
            $params["l"]=$row['l'];
            $params["m"]=$row['m'];
            $params["n"]=$row['n'];
            $params["o"]=$row['o'];
            $params["p"]=$row['p'];
            $params["q"]=$row['q'];
            $params["r"]=$row['r'];
            $params["s"]=$row['s'];
            $params["t"]=$row['t'];
            $params["u"]=$row['u'];
            $params["v"]=$row['v'];
            $params["w"]=$row['w'];
            $params["x"]=$row['x'];
            $params["y"]=$row['y'];
            $params["z"]=$row['z'];
            $params["aa"]=$row['aa'];
            $params["ab"]=$row['ab'];
            $params["ac"]=$row['ac'];
            $params["ad"]=$row['ad'];
            $params["ae"]=$row['ae'];
            $params["af"]=$row['af'];
            $params["ag"]=$row['ag'];
            
  
               
          $collection=  $this->Recovery_collection_model->get_monthly_recovery_collection($village_id,$row['recovery_id'],$month,$year)   ;

            if(  $collection==null){
               $recovery_id = $this->Recovery_collection_model->add_recovery_collection($params);
            }
           
        }

    }

    }

    function remove($village_recovery_id)
    {
		 
        $recovery = $this->Village_recovery_model->get_village_recovery($village_recovery_id);

        // check if the recovery exists before trying to delete it
        if(isset($recovery['village_recovery_id']))
        {
            $delete_result = $this->Village_recovery_model->delete_village_recovery($village_recovery_id);
            redirect("Village_recovery/index");
			 
            
        }
        else
            show_error('The recovery you are trying to delete does not exist.');
    }
    function get_all_village_recovery(){

        $month=$this->input->post('month');
             $year=$this->input->post('year');
            $date_entry="01-$month-$year";
              $prev_date_entry= date('Y-m-d', strtotime('-1 day', strtotime($date_entry)));
            $prev_year= date('Y', strtotime($prev_date_entry));
            $prev_month= date('m', strtotime($prev_date_entry));


        $all_village_recovery=array();
        $username= $this->session->userdata("username");
        $village=$this->Village_model->get_village_by_username($username);
        if($village!=null){
            $village_id=  $village["village_id"];
            $all_vr = $this->Recovery_model->get_add_recovery_join_query();
            foreach( $all_vr as $vr){
                
                $recovery_id= $vr["recovery_id"];

                $recovery_collection=$this->Recovery_collection_model->get_village_recovery_collection_by_village_id_fk_recovery_id($village_id,$prev_month,$prev_year,$recovery_id);


                $vr["b"]=0;
                $vr["c"]=0;
                $vr["d"]=($recovery_collection!=null)? $recovery_collection['f']:0;
                $vr["e"]=($recovery_collection!=null)? $recovery_collection['g']:0;;
                $vr["f"]=0;
                $vr["g"]=0;
                $vr["h"]=0;
                $vr["i"]=0;
                $vr["j"]=0;
                $vr["k"]=0;
                 $vr["l"]=0;
                 $vr["m"]=0;
                 $vr["n"]=0;
                 $vr["o"]=0;
                 $vr["p"]=0;
                 $vr["q"]=0;
                 $vr["r"]=0;
                 $vr["s"]=0;
                 $vr["t"]=0;
                 $vr["u"]=0;
                 $vr["v"]=0;
                 $vr["w"]=0;
                 $vr["x"]=0;
                 $vr["y"]=0;
                 $vr["z"]=($recovery_collection!=null)? $recovery_collection['ab']:0;;
                 $vr["aa"]=($recovery_collection!=null)? $recovery_collection['ac']:0;;
                 $vr["ab"]=0;
                 $vr["ac"]=0;
                 $vr["ad"]=0;
                 $vr["ae"]=0;
                 $vr["af"]=0;
                 $vr["ag"]=0;
                 $vr["ah"]=0;
                 $vr["month"]="";
                 $vr["year"]="";
                 
                 $all_village_recovery[]=$vr;

            }
        }



        echo json_encode($all_village_recovery);
    }

    
    function updateMontlyCollection(){
     
        
     
      $recoveries = $this->input->post('recoveries');

       foreach($recoveries as $row){
           
           $params=array();
        
           $params["b"]=$row['b'];
           $params["c"]=$row['c'];
           $params["d"]=$row['d'];
           $params["e"]=$row['e'];
           $params["f"]=$row['f'];
           $params["g"]=$row['g'];
           $params["h"]=$row['h'];
           $params["i"]=$row['i'];
           $params["j"]=$row['j'];
           $params["k"]=$row['k'];
           $params["l"]=$row['l'];
           $params["m"]=$row['m'];
           $params["n"]=$row['n'];
           $params["o"]=$row['o'];
           $params["p"]=$row['p'];
           $params["q"]=$row['q'];
           $params["r"]=$row['r'];
           $params["s"]=$row['s'];
           $params["t"]=$row['t'];
           $params["u"]=$row['u'];
           $params["v"]=$row['v'];
           $params["w"]=$row['w'];
           $params["x"]=$row['x'];
           $params["y"]=$row['y'];
           $params["z"]=$row['z'];
           $params["aa"]=$row['aa'];
           $params["ab"]=$row['ab'];
           $params["ac"]=$row['ac'];
           $params["ad"]=$row['ad'];
           $params["ae"]=$row['ae'];
           $params["af"]=$row['af'];
           $params["ag"]=$row['ag'];
           
           $primary_key=$row['recovery_collection_id'];
              
         $collection=  $this->Recovery_collection_model->update_recovery_collection($primary_key, $params)   ;

          
          
       }



   }
    
}
