<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Village extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        
		$this->load->model('Village_model');
        $this->load->model('Login_model');
        
    }
 
	
	function index()
    {
	 	
        $data  = array();


        $this->load->library('form_validation');
        
		$this->form_validation->set_rules('village_name','name','required');
		$this->form_validation->set_rules('fk_username','username','required|is_unique[login.username]');
        $this->form_validation->set_rules('password','password','required');
        
		if($this->form_validation->run())     
        {   
		    
            $params = array(
				'village_name' => $this->input->post('village_name'),
				'fk_username' => $this->input->post('fk_username'),
			);
            
          $this->Village_model->add_village($params);


          $params2 = array(
            'username' => $this->input->post('fk_username'),
            'password' => $this->input->post('password'),
            'user_type' => 'village',
            
        );
        
      $this->Login_model->add_login($params2);



         // $flash["message"]='Village successfully created';
          //$flash["class"]="success";       
        //  $this->session->set_flashdata('toast_message',$flash);
         redirect('Village/index');
         
            
        } 






        $data["villages"]=  $this->Village_model->get_all_village();

		$data["_view"] = "village/index" ;
        $this->load->view('layouts/main',$data);
		 
    }
	 
    
 

    function delete_village($village_id){
 

        $data["village"]=  $this->Village_model->get_village($village_id);
        if($data["village"]!=null){

            $fk_username= $data["village"]["fk_username"];
            $this->Login_model->delete_login($fk_username);
            $this->Village_model->delete_village($village_id);
            $flash["message"]='Village successfully deleted';
              $flash["class"]="success";       
              $this->session->set_flashdata('toast_message',$flash); 
              redirect('Village/index');



        }else{
            echo "No data found....";
        }
        

       
    }


    function edit($village_id)
    {   
        
         
        
        // check if the category exists before trying to edit it
        $data["village"]=  $this->Village_model->get_village($village_id);
        
        if(isset($data['village']['village_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('village_name','Village Name','required');
            $this->form_validation->set_rules('fk_username','UserName','required|trim');
		    
            $username= $this->input->post('fk_username');
            if($username != $data['village']['fk_username']){
                $this->form_validation->set_rules('fk_username','username','required|trim|is_unique[login.username]');

            }

           


			if($this->form_validation->run())     
            {
                
                if($username != $data['village']['fk_username']){
                    $params2["username"]=$username;
                    $this->Login_model->update_login($data['village']['fk_username'],$params2);
    
                }
               
                

                $params = array(
					'village_name' => $this->input->post('village_name'),
                    'fk_username' => $this->input->post('fk_username'),
                    
                );
                $this->Village_model->update_village($village_id,$params); 
               
                ?>
                   <script type="text/javascript">
                       alert("Updated Successfully");
                          location.href="<?php echo base_url()?>index.php/village/index";
                    </script>
             
                <?php 
               
            }
            
               
                $data['_view'] = 'village/edit';
                $this->load->view('layouts/main',$data);
           
        }
        else
            show_error('The category you are trying to edit does not exist.');
    } 

}
